url: https://oxydev.ir
baseurl: ""

# Site settings
title: OxyDev
email: szafarpoor@ce.sharif.edu
description: "OxyDev Developers from Sharif University of Technology"


# Team names, titles and social links
people:
- name: Ahmad Salimi
  pic: ahmadsalimi
  position: CTO & Dev
  social:
    - title: twitter
      url: https://twitter.com/ChichekaMan
    - title: github
      url: https://github.com/ahmadsalimi
    - title: linkedin
      url: https://linkedin.com/in/ahmadsalimi
      
- name: Saber Zafarpoor
  pic: saberzafarpour
  position: CEO & Dev
  social:
    - title: github
      url: https://github.com/saberDotCoder
    - title: linkedin
      url: https://linkedin.com/in/szafarpoor

- name: Hadi Esna
  pic: hadiesna
  position: Team Coordinator & Dev
  social:
    - title: github
      url: https://github.com/hadiesna
    - title: linkedin
      url: https://www.linkedin.com/in/hadiesnaashari/

- name: Sepehr Ilami
  pic: alirezailami
  position: CFO & Dev
  social:
    - title: github
      url: https://github.com/sepehrilami
    - title: linkedin
      url: https://www.linkedin.com/in/alirezailami/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket 
    url:
  - title: github
    url: https://github.com/oxydev

# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
